alias dm='docker-machine'
alias dc='docker-compose'
alias de='docker exec -ti'
alias dps='docker ps'
alias di='docker images'
alias drm='docker rm'
alias drmi='docker rmi'
alias dr='docker run'
alias ds='docker start'
alias dst='docker stop'
alias db='docker build'

alias deval='eval $(docker-machine env $0)'
alias drmi0='docker rmi $(docker images | grep "^<none>" | awk "{print $3}")'
